### ISSUE TITLE
purge only uploaded file?

### ISSUE THREAD

**Issue by spormeon** [rudijs/aws-cloudfront-create-invalidation#5]
Hi

can this be used to purge only uploaded file rather than purge everything?  if so, any idea how to do it, as i have no clue.

**Comment by rudijs** [comment]
Yes,

Just pass in the the path to the file name

> # PATHS: "<string> <string>" # Optional. Space separated one or more paths (ex: "/index.html /404.html"). Default is '/*' (everything)
